# Generated by Django 4.1.7 on 2023-03-30 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('ID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Tipo', models.CharField(max_length=20)),
                ('Sexo', models.CharField(max_length=20)),
                ('Raza', models.CharField(max_length=50)),
                ('Birth', models.DateTimeField(auto_now_add=True)),
                ('Location', models.CharField(max_length=50)),
                ('Descripcion', models.TextField()),
                ('Salud', models.TextField()),
                ('Foto1', models.ImageField(upload_to='')),
                ('Foto2', models.ImageField(upload_to='')),
                ('Foto3', models.ImageField(upload_to='')),
                ('Foto4', models.ImageField(upload_to='')),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Adoptante',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=100)),
                ('Cedula', models.CharField(max_length=11)),
                ('Direccion', models.CharField(max_length=120)),
                ('Sector', models.CharField(max_length=100)),
                ('Ciudad', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=60)),
                ('Telefono', models.CharField(max_length=10)),
                ('Animal_Adoptado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dottare_cliente.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Exp_Mascotas',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Pregunta1Si_No', models.CharField(max_length=2)),
                ('Pregunta2', models.CharField(max_length=150)),
                ('Pregunta3', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Pregunta4', models.CharField(max_length=150)),
                ('Pregunta5Si_No', models.CharField(max_length=2)),
                ('Pregunta5', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Pregunta6Si_No', models.CharField(max_length=2)),
                ('Pregunta6VETERINARIO', models.CharField(max_length=150)),
                ('Pregunta6VETERINARIO_TEL', models.CharField(max_length=11)),
                ('Pregunta7Si_No', models.CharField(max_length=2)),
                ('Pregunta7', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Form_Contact',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=60)),
                ('Apellido', models.CharField(max_length=60)),
                ('Email', models.CharField(max_length=60)),
                ('Telefono', models.CharField(max_length=10)),
                ('HorarioParaContactar', models.DateTimeField(auto_now_add=True)),
                ('Mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Form_Donacion',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=60)),
                ('Telefono', models.CharField(max_length=10)),
                ('Monto', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Futuro_Mascota',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Pregunta1', models.CharField(max_length=150)),
                ('Pregunta2', models.CharField(max_length=150)),
                ('Pregunta3', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Info_Hogar',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Pregunta1', models.IntegerField()),
                ('Pregunta2Si_No', models.CharField(max_length=2)),
                ('Pregunta3Si_No', models.CharField(max_length=2)),
                ('Pregunta4Si_No', models.CharField(max_length=2)),
                ('Pregunta4', models.CharField(max_length=150)),
                ('Pregunta5', models.CharField(max_length=150)),
                ('Pregunta6', models.CharField(max_length=150)),
                ('Pregunta7Si_No', models.CharField(max_length=2)),
                ('Pregunta8', models.CharField(max_length=150)),
                ('Pregunta9', models.CharField(max_length=150)),
                ('Pregunta10Si_No', models.CharField(max_length=2)),
                ('Pregunta10', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Info_Personal',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Pregunta1', models.CharField(max_length=150)),
                ('Pregunta2Si_No', models.CharField(max_length=2)),
                ('Pregunta2', models.CharField(max_length=150)),
                ('Pregunta3', models.CharField(max_length=150)),
                ('Pregunta4Si_No', models.CharField(max_length=2)),
                ('Pregunta4', models.CharField(max_length=150)),
                ('Pregunta5', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Form_Info_Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Animal', models.CharField(max_length=50)),
                ('Nombre_Cliente', models.CharField(max_length=60)),
                ('Apellido_Cliente', models.CharField(max_length=60)),
                ('Email', models.CharField(max_length=60)),
                ('Asunto', models.CharField(max_length=30)),
                ('Mensaje', models.TextField()),
                ('ID_Animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dottare_cliente.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Form_Adop',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ID_Adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_adop_id_adoptante', to='dottare_cliente.datos_adoptante')),
                ('ID_EXP', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dottare_cliente.exp_mascotas')),
                ('ID_FUTUROMASCOTA', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dottare_cliente.futuro_mascota')),
                ('ID_INFOHOGAR', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dottare_cliente.info_hogar')),
                ('ID_INFOPERSONAL', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dottare_cliente.info_personal')),
            ],
        ),
    ]
