# Generated by Django 4.1.7 on 2023-03-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dottare_cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='Edad',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
