# Generated by Django 4.2 on 2023-04-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dottare_cliente', '0002_animal_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_contact',
            name='HorarioParaContactar',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
