# Generated by Django 4.2 on 2023-04-11 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dottare_cliente', '0003_alter_form_contact_horarioparacontactar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_donacion',
            old_name='Email',
            new_name='Email2',
        ),
        migrations.RenameField(
            model_name='form_donacion',
            old_name='Telefono',
            new_name='Telefono2',
        ),
    ]
